### ISSUE TITLE
install fail using cpanm

### ISSUE THREAD

**Issue by swuecho** [mschilli/net-evernote-simple#2]
➜  ~  cpanm Net::Evernote::Simple
--> Working on Net::Evernote::Simple
Fetching http://www.cpan.org/authors/id/M/MS/MSCHILLI/Net-Evernote-Simple-0.05.tar.gz ... OK
Configuring Net-Evernote-Simple-0.05 ... OK
==> Found dependencies: Thrift
Found Thrift 0.008000 which doesn't satisfy 0.6.
! Installing the dependencies failed: Installed version (0.8.0) of Thrift is not in range '0.6'
! Bailing out the installation for Net-Evernote-Simple-0.05.

**Comment by mschilli** [comment]
This seems to be caused by a module used by cpanm, namely CPAN::Meta::Requirements, which apparently thinks that Thrift-0.8.0 does not fulfill Net::Evernote::Simple's requirement of Thrift >= 0.6.
 
I've opened an issue over there to see what the deal is:

    https://github.com/Perl-Toolchain-Gang/CPAN-Meta-Requirements/issues/29

If they won't budge, I guess I can change the requirement from "0.6" to "0.6.0", although I'd rather see the root cause fixed.

**Comment by mschilli** [comment]
I've changed the requirement on Thrift from 0.6 to 0.6.1 which should take care of the the 3-number scheme going forward. Please verify the fix in Net::Evernote::Simple 0.06 which should be arriving on your CPAN mirror soon. Thanks for your report!

**Comment by swuecho** [comment]
thanks. works great.
